package com.mryqr.core.common.domain.display;

public enum DisplayValueType {
    TEXT_DISPLAY_VALUE,
    ADDRESS_DISPLAY_VALUE,
    TEXT_OPTIONS_DISPLAY_VALUE,
    FILES_DISPLAY_VALUE,
    GEOLOCATION_DISPLAY_VALUE,
    ITEM_COUNT_DISPLAY_VALUE,
    TEXT_OPTION_DISPLAY_VALUE,
    POINT_CHECK_DISPLAY_VALUE,
    BOOLEAN_DISPLAY_VALUE,
    NUMBER_DISPLAY_VALUE,
    EMAILED_MEMBER_DISPLAY_VALUE,
    MOBILE_MEMBER_DISPLAY_VALUE,
    EMAILED_MEMBERS_DISPLAY_VALUE,
    MOBILE_MEMBERS_DISPLAY_VALUE,
    TIMESTAMP_DISPLAY_VALUE,
}
