package com.mryqr.core.app.domain.report.chart;

public enum ChartReportType {
    CONTROL_BAR_REPORT,
    CONTROL_DOUGHNUT_REPORT,
    CONTROL_NUMBER_RANGE_REPORT,
    CONTROL_PIE_REPORT,
    CONTROL_TIME_SEGMENT_REPORT,
    ATTRIBUTE_BAR_REPORT,
    ATTRIBUTE_DOUGHNUT_REPORT,
    ATTRIBUTE_NUMBER_RANGE_SEGMENT_REPORT,
    ATTRIBUTE_PIE_REPORT,
    ATTRIBUTE_TIME_SEGMENT_REPORT
}
